general {
    lock_cmd = pidof hyprlock || hyprlock       # Was passiert beim Locken?
    before_sleep_cmd = loginctl lock-session  && asusctl leds set off   # Bevor der PC schläft -> Locken
    after_sleep_cmd = hyprctl dispatch dpms on && asusctl leds set high && brightnessctl set 100%  # Nach dem Aufwachen -> Bildschirm an
}

listener {
    timeout = 60
    on-timeout = asusctl leds set off
    on-resume = asusctl leds set high
}
listener {
    timeout = 120
    on-timeout = brightnessctl set 50%     # -> Lockscreen an
    on-resume = brightnessctl set 100%
}
listener {
    timeout = 240                               # 5 Minuten Inaktivität
    on-timeout = loginctl lock-session 
}

listener {
    timeout = 300                                # 10 Minuten Inaktivität
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on 
}
listener {
    timeout = 600                                # 30min
    on-timeout = systemctl suspend-then-hibernate                # suspend pc
    on-resume = nmcli device wifi rescan
} 
